models.1=2
name.1=iregex:(Black White)

models.2=3
name.2=iregex:(King of greed)

models.3=4
name.3=iregex:(Lord of Infurrum)

models.4=5
name.4=iregex:(Avatar of Emptiness)

models.5=7
name.5=iregex:(Mis Q)

models.6=8
name.6=iregex:(Mis Q FINAL FORM)

models.7=9
name.7=iregex:(Chiyako radioactive)

models.8=10
name.8=iregex:(Chiyako queen of the sea)

models.9=11
name.9=iregex:(Chiyako the fallen)

models.10=12
name.10=iregex:(Chiyako the hunter)

models.11=13
name.11=iregex:(Sunny Black white)

models.12=14
name.12=iregex:(Sunny The fallen)

models.13=15
name.13=iregex:(Sunny Billionaire)

models.14=16
name.14=iregex:(Sunny Dreamer)


models.15=6

