
nbt.1.SleepingX=exists:false
models.1=2
name.1=iregex:(aina)

nbt.2.SleepingX=exists:true
models.2=3
name.2=iregex:(aina)

nbt.3.SleepingX=exists:false
models.3=4
name.3=iregex:(Whitenight)

nbt.4.SleepingX=exists:true
models.4=5
name.4=iregex:(Whitenight)

nbt.5.SleepingX=exists:false
models.5=6
name.5=iregex:(Sara)

nbt.6.SleepingX=exists:true
models.6=7
name.6=iregex:(Sara)

nbt.7.SleepingX=exists:false
models.7=8
name.7=iregex:(angela)

nbt.8.SleepingX=exists:true
models.8=9
name.8=iregex:(angela)

nbt.9.SleepingX=exists:false
models.9=10
name.9=iregex:(elija)

nbt.10.SleepingX=exists:true
models.10=11
name.10=iregex:(elija)

nbt.11.SleepingX=exists:false
models.11=12
name.11=iregex:(ryan)

nbt.12.SleepingX=exists:true
models.12=13
name.12=iregex:(ryan)

nbt.13.SleepingX=exists:false
models.13=14
name.13=iregex:(mina)

nbt.14.SleepingX=exists:true
models.14=15
name.14=iregex:(mina)


nbt.15.SleepingX=exists:false
models.15=16
name.15=iregex:(benjamin)

nbt.16.SleepingX=exists:true
models.16=17
name.16=iregex:(benjamin)

nbt.17.SleepingX=exists:false
models.17=18
name.17=iregex:(Rin)

nbt.18.SleepingX=exists:true
models.18=19
name.18=iregex:(Rin)

nbt.19.SleepingX=exists:false
models.19=20
name.19=iregex:(Kety)

nbt.20.SleepingX=exists:false
models.20=21
name.20=iregex:(Stella)

nbt.21.SleepingX=exists:false
models.21=22
name.21=iregex:(Astraea)

nbt.22.SleepingX=exists:false
models.22=23
name.22=iregex:(Nathan)

nbt.23.SleepingX=exists:false
models.23=24
name.23=iregex:(aina swimsuit)

nbt.24.SleepingX=exists:false
models.24=25
name.24=iregex:(aina dress)

nbt.25.SleepingX=exists:false
models.25=26
name.25=iregex:(Nathan suit)

nbt.26.SleepingX=exists:false
models.26=27
name.26=iregex:(Aina work)

nbt.27.SleepingX=exists:false
models.27=28
name.27=iregex:(Stefan)

nbt.28.SleepingX=exists:false
models.28=29
name.28=iregex:(fang)

nbt.29.SleepingX=exists:false
models.29=30
name.29=iregex:(Arin work)

nbt.30.SleepingX=exists:false
models.30=31
name.30=iregex:(Nori)

nbt.31.SleepingX=exists:false
models.31=32
name.31=iregex:(Shine)

nbt.32.SleepingX=exists:false
models.32=33
name.32=iregex:(Xiver)

nbt.33.SleepingX=exists:false
models.33=34
name.33=iregex:(Marquis)

nbt.34.SleepingX=exists:false
models.34=35
name.34=iregex:(Aurora)

nbt.35.SleepingX=exists:false
models.35=36
name.35=iregex:(Midas)

nbt.36.SleepingX=exists:false
models.36=37
name.36=iregex:(Aina foxain)

nbt.37.SleepingX=exists:false
models.37=38
name.37=iregex:(Arin)

nbt.38.SleepingX=exists:false
models.38=39
name.38=iregex:(Victoria)

nbt.39.SleepingX=exists:false
models.39=40
name.39=iregex:(Victoria work)
