name: Auto Release ZIP

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r project.zip . -x ".git/*"

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: project.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}